# Generated by Django 2.0.1 on 2018-02-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180205_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='meuns',
            field=models.ManyToManyField(blank=True, to='crm.Menu'),
        ),
    ]
